### ISSUE TITLE
Certificate verify failed (_ssl.c:645)

### ISSUE THREAD

**Issue by aditiapratama** [CGCookie/blender-addon-updater#16]
I've got SSL certificate verify failed, when pressed the button, any hints fo this

below the error log

```
Traceback (most recent call last):
  File "/usr/local/blender/2.78/python/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/blender/2.78/python/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aditia/.config/blender/2.78/scripts/addons/PSTools/addon_updater.py", line 1033, in async_check_update
    self.check_for_update(now=now)
  File "/home/aditia/.config/blender/2.78/scripts/addons/PSTools/addon_updater.py", line 783, in check_for_update
    self.get_tags() # sets self._tags and self._tag_latest
  File "/home/aditia/.config/blender/2.78/scripts/addons/PSTools/addon_updater.py", line 412, in get_tags
    self._prefiltered_tag_count = len(all_tags)
TypeError: object of type 'NoneType' has no len()

```

**Comment by aditiapratama** [comment]
I'm testing using other add-on such as CrowdMaster, I've got the following error

```
Traceback (most recent call last):
  File "/usr/local/blender/2.78/python/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/blender/2.78/python/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/blender/2.78/python/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/blender/2.78/python/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/blender/2.78/python/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/blender/2.78/python/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/blender/2.78/python/lib/python3.5/http/client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "/usr/local/blender/2.78/python/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/local/blender/2.78/python/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/local/blender/2.78/python/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/blender/2.78/python/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aditia/.config/blender/2.78/scripts/addons/CrowdMaster/addon_updater.py", line 354, in get_api_raw
    result = urllib.request.urlopen(request)
  File "/usr/local/blender/2.78/python/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/blender/2.78/python/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/blender/2.78/python/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/blender/2.78/python/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/blender/2.78/python/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/blender/2.78/python/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/blender/2.78/python/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/blender/2.78/python/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aditia/.config/blender/2.78/scripts/addons/CrowdMaster/addon_updater.py", line 874, in async_check_update
    self.check_for_update(now=now)
  File "/home/aditia/.config/blender/2.78/scripts/addons/CrowdMaster/addon_updater.py", line 664, in check_for_update
    self.get_tags() # sets self._tags and self._tag_latest
  File "/home/aditia/.config/blender/2.78/scripts/addons/CrowdMaster/addon_updater.py", line 341, in get_tags
    self._tags = self.get_api(request)
  File "/home/aditia/.config/blender/2.78/scripts/addons/CrowdMaster/addon_updater.py", line 372, in get_api
    get = self.get_api_raw(url) # this can fail by self-created error raising
  File "/home/aditia/.config/blender/2.78/scripts/addons/CrowdMaster/addon_updater.py", line 359, in get_api_raw
    raise ValueError("URLError, reason: ",e.reason)
ValueError: ('URLError, reason: ', SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'))

```

**Comment by aditiapratama** [comment]
I suspect this is issue with my OS, I'll investigate further

**Comment by aditiapratama** [comment]
I test it using the latest Blender Master Build and it works. It's still broken tho in latest Blender 2.78a release here in Linux fedora 25. I'll close for now.
